### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by liger1978** [joshmn/mattermost-ruby#3]
Can we have a new gem release?

**Comment by joshmn** [comment]
Hey @liger1978 — you know, I'm kind of waiting on APIv4 of Mattermost to be fully released before I go ahead and release some changes. Is there something specific you're looking for?

**Comment by liger1978** [comment]
Just the dependency fix.

**Comment by joshmn** [comment]
@liger1978 oops, sorry for the dumb question; I've been emotionally/mentally invested in Zelda lately and my brain sure shows it.

```
Joshs-MBP:mattermost-ruby josh$ gem push mattermost-ruby-0.4.gem
Pushing gem to https://rubygems.org...
Successfully registered gem: mattermost-ruby (0.4)
```

Pushed!
